export const MODALITY_OPTIONS = [
  'X-Ray Chest',
  'X-Ray Spine',
  'X-Ray Extremities',
  'X-Ray Pelvis',
  'X-Ray Abdomen',
  'X-Ray Neck',
  'X-Ray Skull / PNS',
  'Fluoroscopy',
  'CT Scan',
  'MRI',
  'Ultrasound',
  'Mammography',
  'General / Other',
];

export interface SystemReportTemplate {
  id: string;
  name: string;
  category: string;
  title: string;
  bodyPart?: string;
  findings: string;
  impression: string;
}

export const RADIOLOGY_TEMPLATES: SystemReportTemplate[] = [
  {
    id: 'abdomen-standing',
    name: 'Abdomen Standing View',
    category: 'X-Ray Abdomen',
    title: 'ABDOMEN STANDING',
    bodyPart: 'ABDOMEN',
    findings: `Distended bowel loops containing gas seen.\n\nNo free gas seen under domes of diaphragm.\n\nNo air fluid levels seen.\n\nNo soft tissue mass or abnormal calcification or calculus seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'abdomen-kub',
    name: 'Abdomen K.U.B.',
    category: 'X-Ray Abdomen',
    title: 'ABDOMEN – K.U.B.',
    bodyPart: 'ABDOMEN',
    findings: `The liver, spleen, kidneys, psoas muscles and urinary bladder cast their normal silhouettes.\n\nBoth flanks are normally contoured.\n\nThere is no evidence of intraabdominal calcification or calculus seen.\n\nNo bony anomaly seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'neck-soft-tissue',
    name: 'Neck Soft Tissue (Normal)',
    category: 'X-Ray Neck',
    title: 'NECK SOFT TISSUE',
    bodyPart: 'NECK',
    findings: `Soft tissue of nasopharynx and pre cervical region normal.\n\nNo pressure impression on airways seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'neck-soft-tissues-adenoids',
    name: 'Neck Soft Tissues (Enlarged Adenoids)',
    category: 'X-Ray Neck',
    title: 'NECK SOFT TISSUES (ENLARGED ADENOIDS)',
    bodyPart: 'NECK',
    findings: `Increased soft tissues in naso-pharynx with pressure impression on airways due to enlarged adenoids.\n\nPrecervical soft tissues are normal.`,
    impression: `Increased soft tissues in naso-pharynx with pressure impression on airways due to enlarged adenoids.`,
  },
  {
    id: 'ankle-ap-lat',
    name: 'Ankle Joint AP/LAT',
    category: 'X-Ray Extremities',
    title: 'ANKLE',
    bodyPart: 'ANKLE',
    findings: `The alignment of bones is normal.\n\nBony density is normal.\n\nThe articular margins are smooth.\n\nThe ankle joint space is normal.\n\nThe soft tissues of the ankle cast their normal silhouettes.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'ascending-urethrogram',
    name: 'Ascending Urethrogram (AUG)',
    category: 'Fluoroscopy',
    title: 'ASCENDING URETHROGRAM',
    bodyPart: 'URETHRA',
    findings: `Plain film:\nNo radioopaque calculus seen in lower genito-urinary tract.\n\nContrast study:\nUnder aseptic precaution cannulation of glans penis done and diluted water soluble contrast injected shows normal anterior and posterior parts of urethra.\nNo stricture seen`,
    impression: `Normal ascending urethrogram.`,
  },
  {
    id: 'barium-enema',
    name: 'Barium Enema Examination',
    category: 'Fluoroscopy',
    title: 'BARIUM ENEMA',
    bodyPart: 'COLON',
    findings: `The passage of barium from the rectum into the sigmoid, descending, transverse and the ascending colon was smooth.\n\nThe entire colon is well distended and shows normal mucosal and haustral pattern.\n\nThere is no evidence of any diverticuli, polyps or ulcers on this study.\n\nNo significant abnormality seen in the colon on this study.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'barium-swallow-iitv',
    name: 'Barium Swallow Under IITV',
    category: 'Fluoroscopy',
    title: 'BARIUM SWALLOW UNDER IITV',
    bodyPart: 'OESOPHAGUS',
    findings: `The antegrade passage of barium bollus through the pharynx and oesophagus was swift and unimpeded.\n\nBoth velleculi, pyriform sinuses and post cricoid region are normal.\n\nThe oesophagus has a normal length, course, calibre, mucosal lining and peristaltic activity.\n\nThe cardio-oesophageal junction is in its normal left subdiaphragmatic location.\n\nThere is no evidence of gastro-oesophageal reflux nor a hiatus hernia.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'both-heels-ap-lat',
    name: 'Both Heels AP/LAT',
    category: 'X-Ray Extremities',
    title: 'BOTH HEELS',
    bodyPart: 'HEEL',
    findings: `Bony density is normal.\n\nThe soft tissues of both heels is normal.\n\nNo bony calcaneal or retrocalcaneal spur seen.\n\nNo fracture or bone erosion seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'both-hips-ap-lat',
    name: 'Both Hips AP/LAT',
    category: 'X-Ray Pelvis',
    title: 'BOTH HIPS',
    bodyPart: 'HIP',
    findings: `The bones of the hip appear normal.\n\nThe articular margin of hip joint space is normal.\n\nSoft tissues around hip are normal.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'both-knees-tkr',
    name: 'Both Knees Total Knee Replacement (TKR)',
    category: 'X-Ray Extremities',
    title: 'BOTH KNEES TKR',
    bodyPart: 'KNEE',
    findings: `Total knee joint replacement prosthesis seen on either sides.\n\nBony density is normal.\n\nSoft tissues around knees is normal.`,
    impression: `Total knee replacement prosthesis seen bilaterally in satisfactory position.`,
  },
  {
    id: 'both-calcaneum-lateral',
    name: 'Both Calcaneum Lateral',
    category: 'X-Ray Extremities',
    title: 'BOTH CALCANEUM LATERAL',
    bodyPart: 'CALCANEUM',
    findings: `Sharp bony calcaneal spur seen in lateral view.\n\nBony density is normal.\n\nSoft tissue of heel appears normal.`,
    impression: `Calcaneal spur noted.`,
  },
  {
    id: 'cervical-spine-ap-lat',
    name: 'Cervical Spine AP/LAT (Spondylosis)',
    category: 'X-Ray Spine',
    title: 'CERVICAL SPINE AP/LAT',
    bodyPart: 'CERVICAL SPINE',
    findings: `There is reduction in the disc spaces of C4-5 and C5-6 with posterior osteophytes due to cervical spondylosis.\n\nThe spine shows normal curvature.\n\nBony density is normal\n\nPre and paravertebral soft tissues are normal\n\nNo soft tissue calcification is seen\n\nNo bony cervical ribs seen`,
    impression: `Cervical spondylosis with reduction of disc space.`,
  },
  {
    id: 'chest-pa',
    name: 'Chest PA View (Normal)',
    category: 'X-Ray Chest',
    title: 'CHEST PA',
    bodyPart: 'CHEST',
    findings: `Both lung fields are normal.\n\nThe heart size appears normal.\n\nThe aortic knuckle is normal.\n\nBoth costo-phrenic angles are normal.\n\nThe bony thorax and both dome of diaphragms appear normal.`,
    impression: `No significant abnormality detected.`,
  },
  {
    id: 'chest-portable',
    name: 'Chest Portable View',
    category: 'X-Ray Chest',
    title: 'CHEST (PORTABLE)',
    bodyPart: 'CHEST',
    findings: `Both lung fields are normal.\n\nBoth costo-phrenic angles are normal.\n\nThe aortic knuckle is normal.\n\nCardiac outline is normal.\n\nBony thorax and both dome of diaphragms appear normal.`,
    impression: `No significant abnormality detected.`,
  },
  {
    id: 'dorso-lumbar-spine-ap-lat',
    name: 'Dorso Lumbar Spine AP/LAT',
    category: 'X-Ray Spine',
    title: 'DORSO LUMBAR SPINE AP AND LATERAL',
    bodyPart: 'DORSO LUMBAR SPINE',
    findings: `Thoraco lumbar spine shows normal curvature and alignment.\n\nVertebral bodies, pedicles and visualized facet joints are normal.\n\nNo evidence of any bone erosions or destruction seen in vertebral bodies.\n\nThe inter-vertebral disc spaces are within normal limits.\n\nNo abnormal para vertebral shadow or calcification is seen.\n\nNo evidence of any spondylolysis or spondylolisthesis noted.\n\nBoth sacro-iliac joints are normal.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'dorsal-spine-ap-lat',
    name: 'Dorsal Spine AP/LAT',
    category: 'X-Ray Spine',
    title: 'DORSAL SPINE AP/LAT',
    bodyPart: 'DORSAL SPINE',
    findings: `The dorsal spine assumes its normal kyphosis.\nIts bony spinal canal has an adequate calibre.\n\nThe dorsal vertebrae appear normally aligned, structured and mineralised.\n\nAll the intervertebral disc spaces are preserved.\nThe paraspinal soft tissues cast their normal silhouettes.\n\nThe ribs seen in these films appear normally structured and mineralised.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'elbow-joint-ap-lat',
    name: 'Elbow Joint AP/LAT',
    category: 'X-Ray Extremities',
    title: 'ELBOW JOINT AP/LAT',
    bodyPart: 'ELBOW',
    findings: `The alignment of bones is normal.\n\nThe bones show normal structure.\n\nThe articular margins are normal.\n\nThe elbow joint space is normal.\n\nThe periarticular soft tissues cast their normal silhouettes.`,
    impression: `NO SIGNIFICANT ABNORMALITY DETECTED`,
  },
  {
    id: 'femur-knee-leg-ap-lat',
    name: 'Femur with Knee & Leg AP/LAT',
    category: 'X-Ray Extremities',
    title: 'FEMUR WITH KNEE AND LEG AP/LAT',
    bodyPart: 'FEMUR',
    findings: `Total knee joint replacement prosthesis seen.\n\nBony density is normal.\n\nSoft tissues of thigh and leg are normal.`,
    impression: `Total knee joint replacement prosthesis seen.`,
  },
  {
    id: 'foot-ap-obl-lat',
    name: 'Foot AP/OBL/LAT',
    category: 'X-Ray Extremities',
    title: 'FOOT AP/OBL/LAT',
    bodyPart: 'FOOT',
    findings: `The alignment of bones is normal.\n\nBony density is normal.\n\nThe various small joints of the foot appear normal.\n\nThe soft tissues in the foot cast their normal silhouettes.`,
    impression: `No significant abnormality seen.`,
  },
  {
    id: 'forearm-ap-lat',
    name: 'Forearm AP/LAT',
    category: 'X-Ray Extremities',
    title: 'FOREARM AP /LAT',
    bodyPart: 'FOREARM',
    findings: `The alignment of bones is normal.\n\nThe visualized bones appear normal\n\nThere is no bone destruction or periosteal reaction seen.\n\nThe bony architecture is normal.\n\nNo soft tissue calcification is seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'hand-ap-obl-lat',
    name: 'Hand AP/OBL/LAT',
    category: 'X-Ray Extremities',
    title: 'HAND AP/OBL/LAT',
    bodyPart: 'HAND',
    findings: `The bones in the hand appear normally structured and mineralised.\n\nTheir various joints exhibit normal articulation.\n\nThe soft tissues in the hand cast their normal silhouettes.`,
    impression: `No significant abnormality seen.`,
  },
  {
    id: 'hsg',
    name: 'Hysterosalpingography (H.S.G.)',
    category: 'Fluoroscopy',
    title: 'H.S.G.',
    bodyPart: 'PELVIS',
    findings: `Under aseptic precaution cannulation of cervix done and ultravist 300 injected under IITV examination.\n\nNormal outline of uterine cavity seen with normal fallopian tubes on either sides.\n\nThere is intraperitoneal spill of contrast on either side suggestive of patent both fallopian tubes.\n\nProcedure was uneventful.`,
    impression: `Normal H.S.G. examination.`,
  },
  {
    id: 'knee-joint-ap-lat',
    name: 'Knee Joint AP/LAT (Normal)',
    category: 'X-Ray Extremities',
    title: 'KNEE JOINT AP/LAT',
    bodyPart: 'KNEE',
    findings: `Bony density is normal.\n\nThe articular margins of knee joint space is normal.\n\nSoft tissues around the knee joint is normal`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'knee-replacement',
    name: 'Knee Joint Replacement',
    category: 'X-Ray Extremities',
    title: 'KNEE JOINT AP/LAT REPLACEMENT',
    bodyPart: 'KNEE',
    findings: `Total knee joint replacement prosthesis seen on right/left side.\nSurgical metallic clips seen anteriorly.\nVisualized bony density is normal.\nSoft tissue around joint appears normal.`,
    impression: `Total knee joint replacement prosthesis noted.`,
  },
  {
    id: 'both-knees-oa2',
    name: 'Both Knees OA2 (with Loose Body)',
    category: 'X-Ray Extremities',
    title: 'BOTH KNEES OA2',
    bodyPart: 'KNEE',
    findings: `There is medial reduction in the joint space with marginal lipping due to osteoarthritic changes.\n\nSoft tissues around the knee joint is normal.\n\nLoose body seen.\n\nBony density is normal.`,
    impression: `Bilateral knee osteoarthritis with loose body.`,
  },
  {
    id: 'both-knees-oa1',
    name: 'Both Knees OA1 (Early Osteoarthritis)',
    category: 'X-Ray Extremities',
    title: 'BOTH KNEES OA1',
    bodyPart: 'KNEE',
    findings: `There is medial reduction in the joint space with marginal lipping due to osteoarthritic changes.\n\nSoft tissues around the knee joint is normal.\nNo loose body seen.\n\nBony density is normal.`,
    impression: `Bilateral early knee osteoarthritis.`,
  },
  {
    id: 'ls-spine-ap',
    name: 'L.S. Spine AP (Scoliosis)',
    category: 'X-Ray Spine',
    title: 'L.S. SPINE AP',
    bodyPart: 'LUMBAR SPINE',
    findings: `Scoliotic deformity of mid lumbar with convexity to the left.\n\nPedicles and spinous processes are normal.\n\nBoth sacro-iliac joints are normal.\n\nBoth psoas shadows are normal.`,
    impression: `Mid lumbar scoliosis with convexity to the left.`,
  },
  {
    id: 'ls-spine-ap-lat-fixation',
    name: 'L.S. Spine Fixation (Rod & Screw)',
    category: 'X-Ray Spine',
    title: 'L.S. SPINE AP/LAT',
    bodyPart: 'LUMBAR SPINE',
    findings: `Rod and screw fixation seen posteriorly at L4-5 with disc prosthesis at L4-5.\n\nLumbar spondylotic changes are seen.\nScoliotic deformity of lower lumbar with convexity to the left.\n\nBoth sacro-iliac joints are normal\n\nBoth psoas shadows are normal`,
    impression: `Posterior rod & screw fixation at L4-L5 level with lumbar spondylosis.`,
  },
  {
    id: 'nasal-bone-lateral',
    name: 'Nasal Bone Both Lateral',
    category: 'X-Ray Skull / PNS',
    title: 'NASAL BONE BOTH LATERAL',
    bodyPart: 'NASAL BONE',
    findings: `Nasal bone normal in density and trabecular pattern.\n\nNo fracture or bone erosion seen.\n\nSoft tissue of nose appears normal.`,
    impression: `Normal nasal bone examination.`,
  },
  {
    id: 'neck-soft-tissues-normal',
    name: 'Neck Soft Tissues (Normal)',
    category: 'X-Ray Neck',
    title: 'NECK SOFT TISSUES',
    bodyPart: 'NECK',
    findings: `Soft tissues of naso-pharynx appears normal.\n\nNo pressure impression seen on airways.\n\nPrecervical soft tissues are normal.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'pns-normal',
    name: 'P.N.S. (Normal)',
    category: 'X-Ray Skull / PNS',
    title: 'P.N.S.',
    bodyPart: 'PNS',
    findings: `The paranasal sinuses appear normally pneumatized.\n\nThe nasal septum is centrally placed.\nBoth nares are clear.\n\nThe facial bones appear normally structured and mineralised.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'pelvis-both-hips-thr',
    name: 'Pelvis with Both Hips (THR)',
    category: 'X-Ray Pelvis',
    title: 'PELVIS WITH BOTH HIPS THR',
    bodyPart: 'PELVIS',
    findings: `Bilateral hip joint replacement prosthesis seen.\n\nBony density is normal.\n\nSoft tissues of the pelvis are normal.`,
    impression: `Bilateral total hip replacement (THR) prosthesis.`,
  },
  {
    id: 'pelvis-both-hips',
    name: 'Pelvis with Both Hips (Normal)',
    category: 'X-Ray Pelvis',
    title: 'PELVIS WITH BOTH HIPS',
    bodyPart: 'PELVIS',
    findings: `Bony density is normal.\n\nThe alignment of bones is normal.\n\nNo fracture is seen.\n\nBoth hip joints and sacro-iliac joints appear normal.\n\nNo abnormal soft tissue calcification is seen.`,
    impression: `NO SIGNIFICANT ABNORMALITY DETECTED`,
  },
  {
    id: 'pns-sinusitis',
    name: 'P.N.S. (Sinusitis)',
    category: 'X-Ray Skull / PNS',
    title: 'P.N .S.(sinusitis)',
    bodyPart: 'PNS',
    findings: `Mucosal thickening seen in both maxillary sinus due to sinusitis.\n\nBoth frontal sinus and ethmoid air cells normal.\n\nNasal septum is in center.\n\nNo bone erosion seen.`,
    impression: `Bilateral maxillary sinusitis.`,
  },
  {
    id: 'ribcage',
    name: 'Ribcage AP/OBL',
    category: 'X-Ray Chest',
    title: 'RIBCAGE',
    bodyPart: 'RIBS',
    findings: `No fracture or bone erosion seen.\n\nNo pleural reaction or pneumothorax formation seen.`,
    impression: `Normal bony ribcage.`,
  },
  {
    id: 'scanogram-leg',
    name: 'Scanogram Leg',
    category: 'X-Ray Extremities',
    title: 'SCANOGRAM LEG',
    bodyPart: 'LEG',
    findings: `Articular margins of both hips and ankle joints are normal.\nBilateral osteoarthritic changes seen in knee joints\nThe right femur measures       cms in length.\nLeft femur measures       cms.\n\nRight tibia measures     cms\nLeft tibia measures        cms\n\nThere is no significant difference in length of femur with tibia seen on either sides.`,
    impression: `Leg scanogram study.`,
  },
  {
    id: 'shoulder-oa',
    name: 'Shoulder AP/LAT (Osteoarthritis)',
    category: 'X-Ray Extremities',
    title: 'SHOULDER AP/LAT OA',
    bodyPart: 'SHOULDER',
    findings: `Osteoarthritic changes seen in both / right / left shoulder\n\nBony density is normal.\n\nThe acromio-clavicular joint is normal.\n\nSoft tissues around joint is normal.`,
    impression: `Osteoarthritis of shoulder joint noted.`,
  },
  {
    id: 'shoulder-normal',
    name: 'Shoulder AP/LAT (Normal)',
    category: 'X-Ray Extremities',
    title: 'SHOULDER (normal)',
    bodyPart: 'SHOULDER',
    findings: `The alignment of bones is normal.\n\nThe bones show normal architecture.\n\nThe shoulder joint space is normal\n\nThe soft tissues in the shoulder cast their normal silhouettes.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'skull-ap-lat',
    name: 'Skull AP/LAT',
    category: 'X-Ray Skull / PNS',
    title: 'SKULL AP/LAT',
    bodyPart: 'SKULL',
    findings: `All the cranial bones appear normally structured and mineralised.\n\nThe sella turcica and its appendages appear normally contoured and mineralised.  The pituitary fossa has a normal size and shape.\n\nThe sutural and vascular markings cast their normal silhouettes.\n\nThere is no evidence of abnormal intracranial calcification.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'wrist-ap-lat',
    name: 'Wrist AP/LAT',
    category: 'X-Ray Extremities',
    title: 'WRIST AP/LAT',
    bodyPart: 'WRIST',
    findings: `The alignment of bones is normal.\n\nThe bones show normal architecture.\n\nThe radio-carpal, intercarpal and carpo-metacarpal joints show normal articular margin and joint spaces.\n\nThe soft tissues in the wrist cast their normal silhouettes.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'scanogram-spine',
    name: 'Scanogram Spine',
    category: 'X-Ray Spine',
    title: 'SCANOGRAM SPINE',
    bodyPart: 'SPINE',
    findings: `Scoliotic deformity at lower dorsal with convexity towards right and compensatory scoliosis at mid lumbar with convexity to left.\n\nParavertebal soft tissues are normal.\n\nBony density is normal.\n\nLength from C1 to L5 is _____ cm.`,
    impression: `Dorsolumbar scoliosis with compensatory curvature.`,
  },
  {
    id: 'coccyx-ap-lat',
    name: 'Coccyx AP/LAT',
    category: 'X-Ray Spine',
    title: 'COCCYX (AP/LAT)',
    bodyPart: 'COCCYX',
    findings: `Bony outline and curvature are normal.\n\nBone density is normal.\n\nNo fracture or bone erosion seen.`,
    impression: `Normal coccyx examination.`,
  },
  {
    id: 'mcu-pm-child',
    name: 'M.C.U. Pediatric',
    category: 'Fluoroscopy',
    title: 'M.C.U. PM for child',
    bodyPart: 'BLADDER',
    findings: `Plain film:  No radioopaque calculus seen in lower genito urinary tract.\n\nConstrast study:  Under aseptic precaution infant feeding tube No. 5 passed from urethral opening to urinary bladder under IITV and diluted water soluble contrast injected.\n\nThere is normal outline of the urinary bladder in full bladder film.\nNo vesico ureteric reflux seen in full bladder and micturating film.\n\nUrethra is normal in its entire length in both oblique micturating films.\n\nNo significant residue of contrast seen in post void film.`,
    impression: `Normal M.C.U. examination.`,
  },
  {
    id: 'thumb-ap-lat',
    name: 'Thumb AP/LAT',
    category: 'X-Ray Extremities',
    title: 'THUMB (AP /LAT)',
    bodyPart: 'THUMB',
    findings: `Bone density is normal.\nInterphalangeal joints appears normal.\nSoft tissues around thumb is normal.`,
    impression: `Normal thumb examination.`,
  },
  {
    id: 'leg-ap-lat',
    name: 'Leg AP/LAT',
    category: 'X-Ray Extremities',
    title: 'LEG',
    bodyPart: 'LEG',
    findings: `The tibia and fibula appear normally structured and mineralised.\n\nThe tibio-fibular and knee/ankle joint exhibits normal articulation.\n\nThe soft tissues in the leg cast their normal silhouettes.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'both-humerus-ap-lat',
    name: 'Both Humerus AP/LAT',
    category: 'X-Ray Extremities',
    title: 'BOTH HUMERUS AP /LAT',
    bodyPart: 'HUMERUS',
    findings: `Visualized humerus appears normal.\n\nBony density is normal.\n\nBoth shoulder joints appear normal.\n\nSoft tissue around shoulder joints and arms is normal.`,
    impression: `Normal bilateral humerus examination.`,
  },
  {
    id: 'ascending-urethrogram-1',
    name: 'Ascending Urethrogram (AUG Alternate)',
    category: 'Fluoroscopy',
    title: 'ASCENDING URETHROGRAM',
    bodyPart: 'URETHRA',
    findings: `Plain film:\nNo radioopaque calculus seen in lower genito-urinary tract.\nContrast study:\nUnder aseptic precaution cannulation of glans penis done and diluted water soluble contrast injected shows normal anterior and posterior parts of urethra.\nNo stricture seen\nProcedure was uneventful.`,
    impression: `Normal ascending urethrogram.`,
  },
  {
    id: 'ls-spine-lateral-flexion',
    name: 'L.S. Spine Lateral Flexion / Extension',
    category: 'X-Ray Spine',
    title: 'L.S. SPINE LATERAL/FLEXION',
    bodyPart: 'LUMBAR SPINE',
    findings: `Lumbar spondylotic changes are seen.\n\nNo spondylolysis or spondylolisthesis is seen\n\nBony density is normal.\n\nNo bone erosion or wedging seen`,
    impression: `Lumbar spondylotic changes.`,
  },
  {
    id: 'aug-mcu-adult',
    name: 'AUG & MCU Adult',
    category: 'Fluoroscopy',
    title: 'ASCENDING URETHROGRAM & MICTURATING CYSTO URETHROGRAM adult',
    bodyPart: 'URETHRA',
    findings: `Plain film:\nNo radioopaque calculus seen in lower genito-urinary tract.\n\nContrast study:\nAscending Urethrogram:\nUnder aseptic precaution cannulation of glans penis done and diluted water soluble contrast injected.\n\nMicturating Cysto-Urethrogam:\nUnder aseptic precaution Infant feeding tube No. 6 passed from urethral opening to urinary bladder and diluted water soluble contrast injected to fill the bladder. Normal outline of the urinary bladder is seen in full bladder film. No vesico ureteric reflux seen in full bladder or micturating films. No significant residue of contrast seen in post void film.\n\nProcedure was uneventful.`,
    impression: `Normal AUG & MCU examination.`,
  },
  {
    id: 'sacrococcyx-ap-lat',
    name: 'Sacrococcyx AP/LAT',
    category: 'X-Ray Spine',
    title: 'SACROCOCCYX (AP/LAT)',
    bodyPart: 'SACROCOCCYX',
    findings: `Bony density and curvature appears normal.\n\nNo fracture or displacement of bones noted.\n\nPrevertebral soft tissues are normal.`,
    impression: `Normal sacrococcyx examination.`,
  },
  {
    id: 'barium-enema-pm',
    name: 'Barium Enema PM',
    category: 'Fluoroscopy',
    title: 'BARIUM ENEMA pm',
    bodyPart: 'COLON',
    findings: `Infant feeding tube number 8 inserted into anal canal and tip kept at rectum and thin barium was injected under IITV.\n\nThe passage of barium from the rectum into the sigmoid, descending, transverse and the ascending colon was smooth.\n\nThe entire colon is well distended and shows normal mucosal and haustral pattern.\n\nThere is no evidence of any diverticuli, polyps or ulcers on this study.\n\nNo significant abnormality seen in the colon on this study.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'barium-swallow-pm',
    name: 'Barium Swallow PM',
    category: 'Fluoroscopy',
    title: 'BARIUM SWALLOW PM',
    bodyPart: 'OESOPHAGUS',
    findings: `There was smooth uninterrupted passage of barium from the oropharynx through the oesophagus into the stomach.\n\nThe Valleculae and the pyriform fossae are normal.\n\nThe cervical and thoracic portions of the oesophagus are normal.\n\nThe gastro-oesophageal junction has a normal sub diaphragmatic location.\n\nThere is no evidence of reflux or hiatus hernia on Valsalva's manoeuvre in Trendenlenberg's position.\n\nNo significant abnormality seen in the oesophagus on this study.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'barium-meal-stomach-duodenum',
    name: 'Barium Meal Stomach / Duodenum',
    category: 'Fluoroscopy',
    title: 'BARIUM MEAL STOMACH/DUODENUM',
    bodyPart: 'STOMACH',
    findings: `The passage of barium through the oesophagus was smooth and unimpeded as viewed under IITV. The cardio-oesophageal junction is in its normal left subdiaphragmatic location.\n\nThe stomach has a normal size and contour.  The gastric mucosal lining appears healthy.  The passage of barium through the pyloric canal was swift and unimpeded.\n\nThe duodenal bulb has a normal size and contour.  The duodenum has a normal orientation, position, length, calibre, mucosal lining and peristaltic activity.`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'barium-meal-follow-through',
    name: 'Barium Meal Follow Through (BMFT)',
    category: 'Fluoroscopy',
    title: 'BARIUM MEAL  FOLLOW THROUGH',
    bodyPart: 'SMALL BOWEL',
    findings: `The passage of barium through the oesophagus was uninterrupted.\n\nThe stomach is of normal size and shape and shows prompt emptying.\n\nThe C loop of the duodenum is normal.\n\nThe passage of barium through the small bowel is normal.  There is no dilatation or stricture formation of the small bowel.\n\nThe terminal ileum and the ileocaecal junction appears normal.\n\nPost air insufflation spot film shows adequate distension of the caecum which has a normal mucosal pattern.\n\nThe appendix is visualised in the 24 hrs. film and is normal`,
    impression: `NO SIGNIFICANT ABNORMALITY SEEN`,
  },
  {
    id: 'tm-joints-open-closed',
    name: 'Temporomandibular Joints (Open/Closed)',
    category: 'X-Ray Skull / PNS',
    title: 'TEMPOROMANDIBULAR JOINTS (OPEN AND CLOSED MOUTH VIEW)',
    bodyPart: 'TMJ',
    findings: `Normal outline of temporomandibular joint in closed mouth view and good movement in open mouth view.\n\nNo bone erosion seen.\n\nBony density is normal.`,
    impression: `Normal TM joint movement bilaterally.`,
  },
  {
    id: 'mandible-ap-obl',
    name: 'Mandible AP/OBL',
    category: 'X-Ray Skull / PNS',
    title: 'MANDIBLE AP/OBL',
    bodyPart: 'MANDIBLE',
    findings: `No fracture or dislocation noted.\n\nThe size and shape of the condylar head are normal.\n\nBony density is normal.\n\nMandibular outline appears normal.\n\nNo fracture or bone erosion seen.`,
    impression: `Normal mandible study.`,
  },
  {
    id: 'distal-loop-cologram',
    name: 'Barium Distal Loop Cologram',
    category: 'Fluoroscopy',
    title: 'BARIUM FOR I/C AND DISTAL LOOP COLOGRAM',
    bodyPart: 'COLON',
    findings: `Colostomy bag noted filled with fecal material and barium with normal proximal bowel loops.\n\nFrom colostomy bag catheter pass in efferent loop under IITV and diluted water soluble contrast injected shows normal hepatic flexure, transverse colon, splenic flexure, descending colon and rectosigmoid region.\n\nNo intraperitoneal leak or obstruction noted.\n\nContrast comes out from anus during procedure.\n\nProcedure was uneventful.`,
    impression: `Normal distal loop cologram and barium for small bowel and I/C region.`,
  },
  {
    id: 'ryles-tube-insertion',
    name: 'Ryle\'s Tube Insertion Under IITV',
    category: 'Fluoroscopy',
    title: 'RYLE’S TUBE INSERTION UNDER IITV',
    bodyPart: 'STOMACH',
    findings: `Under local anesthesia of right nostril and oropharynx.\n\nRyle’s tube insertion from right nostril and tip kept at stomach\nConfirmed by ingesting contrast.\n\nProcedure was uneventful.`,
    impression: `Successful Ryle's tube placement in stomach.`,
  },
];
